### PR TITLE
Simplify cumulative max

### LINKED ISSUE #25: cumulativeMax method over estimates the true cumulative max
right now the cumulative max is calculated by adding together the max of each dataset. This is incorrect.  It should add each piece of data for each bar, and return the max of those. This is complicated by the fact that datasets are not necessarily ordered in bar order, so it will be necessary to first group each datasets into bars.

### LINKED ISSUE #69: remove forced 1% on bars
https://github.com/FormidableLabs/victory-bar/blob/d9cc5e1aac9f37945fcaaea3bd37afd9c48e0df6/src/components/victory-bar.jsx#L392

This causes padding issue shown here (the bit to the left of the red):

http://vgy.me/S2a9lQ.png

Temp fix is to use negative padding

### PR DESCRIPTION
**Pull request by boygirl**
cc/ @coopy or @knowbody (if you have time)

This PR correctly calculates the cumulative min and max for stacked bar charts. I've also done a bit of code clean up.

closes #25 
closes #69

### CODE REVIEW

File: src/components/victory-bar.jsx [hunk 1]
```diff
@@ -358,72 +369,96 @@ export default class VictoryBar extends React.Component {
     if (axis !== "x" || !props.categories || Util.Collection.containsStrings(props.categories)) {
       return undefined;
     }
-    return [_.min(_.flatten(props.categories)), _.max(_.flatten(props.categories))];
+    return [Math.min(..._.flatten(props.categories)), Math.max(..._.flatten(props.categories))];
```
Comment (knowbody) [inline src/components/victory-bar.jsx]: maybe a silly question but what does this do:

``` js
..._.flatten()
```

I'm confused by that

Comment (boygirl) [inline src/components/victory-bar.jsx]: grabs all of the values out of the resulting array. `Math.min` expects a list of args instead of an array. Does look pretty ugly though

**Comment by coopy** [comment]
Looks clean! Some unit test coverage would be good so we don't step backwards.

**Comment by boygirl** [comment]
cc/ @coopy 

I decided to lump in a fix for #69 with this work to make it easier to write tests.

**Comment by coopy** [comment]
Awesome! :+1:

**Comment by boygirl** [comment]
Travis, why?

**Comment by coopy** [comment]
My bad, @boygirl. Fixing.
